# Generated by Django 2.2.2 on 2019-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Id')),
                ('firstname', models.CharField(max_length=64, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=64, verbose_name='Lastname')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
            ],
        ),
    ]
