# Generated by Django 2.2.2 on 2019-06-21 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, unique=True, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
